/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Calculator: typeof import('./src/components/calculator.vue')['default']
    CheckOperation: typeof import('./src/components/CheckOperation.vue')['default']
    Header: typeof import('./src/components/layout/header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    OrderList: typeof import('./src/components/order/OrderList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchItem: typeof import('./src/components/search/searchItem.vue')['default']
    SearchList: typeof import('./src/components/search/searchList.vue')['default']
    ShoppingItem: typeof import('./src/components/cart/shoppingItem.vue')['default']
    ShoppingList: typeof import('./src/components/cart/shoppingList.vue')['default']
  }
}
